apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightrag.fullname" . }}-env
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |-
    {{- include "lightrag.envContent" . | nindent 4 }}
