apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightrag.fullname" . }}
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.PORT }}
      protocol: TCP
      name: http
  selector:
    {{- include "lightrag.selectorLabels" . | nindent 4 }}
