name: Bug Report
description: 提交 bug
title: "[Bug]: <title>"
labels: ["bug", "triage"]

body:
  - type: checkboxes
    id: existingcheck
    attributes:
      label: 是否需要提交问题？
      description: 请通过以下步骤避免重复和常见的 bug。
      options:
        - label: 我已经搜索过现有的问题，这个 bug 还没有被报告。
        - label: 我认为这是一个合法的 bug，而不是一个问题或功能请求。
  - type: textarea
    id: description
    attributes:
      label: 描述 bug
      description: 清晰简洁地描述 bug 的问题。
      placeholder: 出现了什么问题？
  - type: textarea
    id: reproduce
    attributes:
      label: 重现步骤
      description: 重现此问题的步骤。
      placeholder: 我们如何复现此问题？
  - type: textarea
    id: expected_behavior
    attributes:
      label: 预期行为
      description: 清晰简洁地描述你预期的结果。
      placeholder: 应该发生什么？
  - type: textarea
    id: configused
    attributes:
      label: 使用的 LightRAG 配置
      description: 运行时使用的 LightRAG 配置。
      placeholder: 配置内容或 LightRAG 配置
      value: |
        # 请粘贴你的配置内容
  - type: textarea
    id: screenshotslogs
    attributes:
      label: 日志和截图
      description: 如有需要，请添加截图和日志以帮助解释你的问题。
      placeholder: 在此添加日志和截图
  - type: textarea
    id: additional_information
    attributes:
      label: 其他信息
      description: |
        - LightRAG 版本：例如 v0.1.1
        - 操作系统：例如 Windows 10，Ubuntu 20.04
        - Python 版本：例如 3.8
        - 相关问题：例如 #1
        - 其他相关信息。
      value: |
        - LightRAG 版本：
        - 操作系统：
        - Python 版本：
        - 相关问题：
