name: Feature Request
description: 提交功能请求
labels: ["enhancement"]
title: "[Feature Request]: <title>"

body:
  - type: checkboxes
    id: existingcheck
    attributes:
      label: 是否需要提交功能请求？
      description: 请通过以下步骤避免重复和常见的功能请求。
      options:
        - label: 我已经搜索过现有的功能请求，这个功能请求还没有被报告。
        - label: 我认为这是一个合法的功能请求，而不是一个问题或 bug。
  - type: textarea
    id: feature_request_description
    attributes:
      label: 功能请求描述
      description: 清晰简洁地描述你希望的功能请求。
      placeholder: 这个功能请求会增加或改进什么？
  - type: textarea
    id: additional_context
    attributes:
      label: 额外上下文
      description: 在此添加任何关于功能请求的其他上下文或截图。
      placeholder: 任何其他信息
