{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lightrag-minimal.fullname" . }}
  labels:
    {{- include "lightrag-minimal.labels" $ | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "lightrag-minimal.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
  {{- else }}
    - host: {{ .Release.Namespace }}.apps.{{ .Values.ingress.clusterName }}.org.neu.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lightrag-minimal.fullname" $ }}
                port:
                  name: http
  {{- end }}
{{- end }}