apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightrag-minimal.secretName" . }}
  labels:
    {{- include "lightrag-minimal.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  llm-api-key: {{ .Values.secrets.llmApiKey | b64enc | quote }}
  embedding-api-key: {{ .Values.secrets.embeddingApiKey | b64enc | quote }}
  lightrag-api-key: {{ .Values.secrets.lightragApiKey | default "" | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- if and .Values.auth.enabled (gt (len .Values.auth.accounts) 0) }}
  auth-accounts: {{ include "lightrag-minimal.authAccounts" . | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.enabled .Values.auth.tokenSecret }}
  token-secret: {{ .Values.auth.tokenSecret | b64enc | quote }}
  {{- end }}
