## description: The version of ElasticSearch.
## default: 8.8.2
version: "8.8.2"

## description: Mode for ElasticSearch
## default: multi-node
## one of: [single-node, multi-node]
mode: single-node

## description: The number of replicas, for single-node mode, the replicas is 1, for multi-node mode, the default replicas is 3.
## default: 1
## minimum: 1
## maximum: 5
replicas: 1

## description: CPU cores.
## default: 1
## minimum: 0.5
## maximum: 64
cpu: 1

## description: Memory, the unit is Gi.
## default: 2
## minimum: 1
## maximum: 1000
memory: 2

## description: Storage size, the unit is Gi.
## default: 20
## minimum: 1
## maximum: 10000
storage: 5

extra:
  terminationPolicy: Delete
  disableExporter: true
