"""Byte-equivalence golden tests for the native docx → SidecarWriter migration.

These tests run the *new* path (``NativeDocxAdapter`` + ``write_sidecar``)
on each scenario in ``_native_docx_fixtures.SCENARIOS`` and assert that
every produced file matches the captured baseline bytes under
``tests/parser_adapters/golden/native_docx/<scenario>/``.

The baseline was generated by ``scripts/regen_native_docx_golden.py``
running against the legacy inline-regex implementation; the script lives
in-tree so the snapshots can be regenerated when intentional changes to
the format are made (e.g. spec evolution).
"""

from __future__ import annotations

import asyncio
import sys
from datetime import datetime, timezone
from pathlib import Path
from unittest import mock

import pytest

# Make the sibling _native_docx_fixtures module importable as if it were a
# top-level helper. Avoids needing a package __init__ rename.
HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from _native_docx_fixtures import SCENARIOS, Scenario  # noqa: E402

GOLDEN_ROOT = HERE / "golden" / "native_docx"


_FROZEN_NOW = datetime(2026, 1, 1, tzinfo=timezone.utc)


class _FrozenDateTime(datetime):
    @classmethod
    def now(cls, tz=None):  # noqa: D401
        return _FROZEN_NOW if tz is None else _FROZEN_NOW.astimezone(tz)


def _run_new_path(scenario: Scenario, out_dir: Path) -> None:
    """Invoke ``parse_docx_to_lightrag_document`` on a single scenario.

    The upstream ``extract_docx_blocks`` is stubbed to feed the synthetic
    blocks and produce the matching asset files inside
    ``<base>.blocks.assets/``. ``datetime.now`` is frozen so ``parse_time``
    matches the captured baseline exactly.
    """
    from lightrag.native_parser.docx import lightrag_adapter

    def _stub_extract(
        file_path,
        *,
        fixlevel=None,
        drawing_context=None,
        parse_warnings=None,
        parse_metadata=None,
        **_kwargs,
    ):
        if drawing_context is not None and scenario.assets:
            drawing_context.export_dir_path.mkdir(parents=True, exist_ok=True)
            for name, data in scenario.assets.items():
                (drawing_context.export_dir_path / name).write_bytes(data)
        if parse_metadata is not None:
            parse_metadata.update(scenario.parse_metadata)
        return [dict(b) for b in scenario.blocks]

    with mock.patch.object(
        lightrag_adapter, "extract_docx_blocks", _stub_extract
    ), mock.patch(
        "lightrag.sidecar.writer.datetime", _FrozenDateTime
    ):

        async def _go():
            await lightrag_adapter.parse_docx_to_lightrag_document(
                file_bytes=b"fake-docx",
                file_path=scenario.file_path,
                doc_id=scenario.doc_id,
                source_path=str(out_dir / scenario.file_path),
                output_dir=out_dir,
            )

        asyncio.run(_go())


def _read_bytes(path: Path) -> bytes:
    with path.open("rb") as fh:
        return fh.read()


@pytest.mark.offline
@pytest.mark.parametrize(
    "scenario",
    SCENARIOS,
    ids=[s.name for s in SCENARIOS],
)
def test_native_docx_migration_is_byte_equivalent(
    scenario: Scenario, tmp_path: Path
) -> None:
    """Every file produced by the new adapter+writer flow must be
    byte-identical to the captured legacy baseline."""
    out_dir = tmp_path / "produced"
    out_dir.mkdir()
    _run_new_path(scenario, out_dir)

    expected_root = GOLDEN_ROOT / scenario.name
    assert expected_root.is_dir(), (
        f"missing golden fixture for scenario {scenario.name!r}; "
        f"run scripts/regen_native_docx_golden.py to regenerate"
    )

    # Collect both file sets relative to their roots, then compare.
    expected_files = {
        p.relative_to(expected_root): p
        for p in expected_root.rglob("*")
        if p.is_file()
    }
    produced_files = {
        p.relative_to(out_dir): p for p in out_dir.rglob("*") if p.is_file()
    }

    extra = sorted(produced_files.keys() - expected_files.keys())
    missing = sorted(expected_files.keys() - produced_files.keys())
    assert not extra, f"unexpected produced files: {extra}"
    assert not missing, f"missing produced files (legacy had them): {missing}"

    mismatches: list[str] = []
    for rel, expected_path in expected_files.items():
        produced_path = produced_files[rel]
        if _read_bytes(produced_path) != _read_bytes(expected_path):
            mismatches.append(str(rel))
    assert not mismatches, (
        f"byte mismatch in scenario {scenario.name!r} for files: {mismatches}"
    )
