{{- if .Values.mongodb.enabled }}
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  terminationPolicy: {{ .Values.global.terminationPolicy }}
  clusterDef: mongodb
  topology: {{ .Values.mongodb.topology }}
  componentSpecs:
    - name: mongodb
      serviceVersion: "{{ .Values.mongodb.serviceVersion }}"
      disableExporter: {{ .Values.mongodb.disableExporter }}
      replicas: {{ .Values.mongodb.replicas }}
      resources:
        {{- toYaml .Values.mongodb.resources | nindent 8 }}
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: "{{ .Values.mongodb.storageClassName }}"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.mongodb.storage }}
{{- end }}
