{{- if .Values.postgresql.enabled }}
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  terminationPolicy: {{ .Values.global.terminationPolicy }}
  clusterDef: postgresql
  topology: replication # As per your example
  componentSpecs:
    - name: postgresql # Default component name for PostgreSQL
      serviceVersion: "{{ .Values.postgresql.serviceVersion }}"
      disableExporter: {{ .Values.postgresql.disableExporter }}
      labels:
        # Specific label for Patroni scope
        apps.kubeblocks.postgres.patroni/scope: {{ .Values.postgresql.name }}-postgresql
      replicas: {{ .Values.postgresql.replicas }}
      systemAccounts:
        - name: postgres
          secretRef:
            name: {{ .Values.postgresql.customSecretName }}
            namespace: {{ .Values.postgresql.customSecretNamespace }}
      resources:
        {{- toYaml .Values.postgresql.resources | nindent 8 }}
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: "" # Or make this configurable if needed
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.postgresql.storage }}
{{- end }}
