{{- if .Values.qdrant.enabled }}
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: {{ .Values.qdrant.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  terminationPolicy: {{ .Values.global.terminationPolicy }}
  clusterDef: qdrant
  topology: cluster # As per your example
  componentSpecs:
    - name: qdrant # Default component name for Qdrant
      serviceVersion: "{{ .Values.qdrant.serviceVersion }}"
      disableExporter: {{ .Values.qdrant.disableExporter }}
      replicas: {{ .Values.qdrant.replicas }}
      resources:
        {{- toYaml .Values.qdrant.resources | nindent 8 }}
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: ""
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.qdrant.storage }}
{{- end }}
